extraction:
  cpp:
    prepare:
      packages:
        - libsamplerate0-dev
        - libsndfile1-dev
        - libspeex-dev
        - libasound2-dev
    configure:
      command:
        - mkdir _lgtm_build_dir
        - cd _lgtm_build_dir
        - cmake -DBUILD_GTEST=OFF -DINSTALL_GTEST=OFF -DCMAKE_BUILD_TYPE=Debug ..
    index:
      build_command:
        - cd _lgtm_build_dir
        - make
